name: Nodejs Hapi Template
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build_and_test:
        if: github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/qa'
        name: Build & Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
              env:
                  CI: true
            - name: Lint
              run: npm run lint
              env:
                  CI: true
            - name: Test
              run: npm run test
              env:
                  CI: true
